project_id = "bvstvawnigyczvofzhps"

[functions.ccmixter-proxy]
verify_jwt = false

[functions.ai-playlist]
verify_jwt = false

[functions.daily-cc-fetch]
verify_jwt = false

[functions.generate-email]
verify_jwt = false

[functions.ai-categorize]
verify_jwt = false

[functions.ai-cover]
verify_jwt = false

[functions.spotify-import]
verify_jwt = false

[functions.ai-suggest-tracks]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.suno-generate]
verify_jwt = false

[functions.ai-mix-suggest]
verify_jwt = false

[functions.send-email]
verify_jwt = false