/**
 * Katalog integracji z urządzeniami i platformami zdrowotnymi.
 *
 * Kolejność w tablicy odpowiada priorytetom produktowym: Garmin pierwszy,
 * potem platformy systemowe (Apple Health, Health Connect), które jednym
 * połączeniem obejmują kilkanaście marek zegarków.
 *
 * `metrics` zawiera wyłącznie te pola, które realnie da się pobrać danym
 * kanałem — to lista kontraktowa dla mapperów w `supabase/functions/stop-aging-sync`.
 */

import type { DataSource, DeviceIntegration } from "./types";

export const DEVICE_INTEGRATIONS: DeviceIntegration[] = [
  {
    id: "garmin",
    name: "Garmin Connect",
    priority: 1,
    transport: "oauth_cloud",
    push: true,
    latencyMin: 5,
    metrics: [
      "heartRate",
      "hrv",
      "hrvStatus",
      "spo2",
      "respiration",
      "bodyBattery",
      "trainingReadiness",
      "stressScore",
      "recoveryTime",
      "sleepStages",
      "sleepScore",
      "vo2Max",
      "enduranceScore",
      "hillScore",
      "steps",
      "calories",
      "distance",
      "workouts",
      "skinTemp",
      "weight",
      "sedentaryTime",
      "naps",
    ],
    notes:
      "Garmin Health API z rejestracją webhooków Push. Jedyne źródło Body Battery, Training Readiness i HRV Status — metryk, których nie da się odtworzyć z surowego tętna.",
  },
  {
    id: "apple_health",
    name: "Apple Health",
    priority: 2,
    transport: "native_sdk",
    push: false,
    latencyMin: 15,
    metrics: [
      "heartRate",
      "hrv",
      "spo2",
      "respiration",
      "ecg",
      "sleepStages",
      "steps",
      "calories",
      "distance",
      "workouts",
      "vo2Max",
      "weight",
      "bodyFat",
      "bloodPressure",
      "skinTemp",
      "standHours",
      "mindfulMinutes",
    ],
    notes:
      "HealthKit działa wyłącznie na urządzeniu — synchronizacja w tle przez background delivery. Obejmuje Apple Watch oraz każdą aplikację zapisującą do Health.",
  },
  {
    id: "health_connect",
    name: "Health Connect (Android)",
    priority: 3,
    transport: "native_sdk",
    push: false,
    latencyMin: 15,
    metrics: [
      "heartRate",
      "hrv",
      "spo2",
      "respiration",
      "sleepStages",
      "steps",
      "calories",
      "distance",
      "workouts",
      "vo2Max",
      "weight",
      "bodyFat",
      "bloodPressure",
      "skinTemp",
      "hydration",
      "nutrition",
    ],
    notes:
      "Jedno połączenie obejmuje Samsung Health, Google Fit, Fitbit, Xiaomi, Amazfit, Honor, Oppo, OnePlus, Realme, Mobvoi i Nothing — o ile producent zapisuje dane do Health Connect.",
  },
  {
    id: "oura",
    name: "Oura Ring",
    priority: 4,
    transport: "oauth_cloud",
    push: true,
    latencyMin: 10,
    metrics: [
      "hrv",
      "heartRate",
      "spo2",
      "respiration",
      "sleepStages",
      "sleepScore",
      "readiness",
      "skinTemp",
      "steps",
      "calories",
      "naps",
      "cycleTracking",
    ],
    notes:
      "Oura API v2 z webhookami. Najlepsza jakość danych nocnych (temperatura skóry, HRV w trakcie snu) przy braku danych treningowych.",
  },
  {
    id: "whoop",
    name: "WHOOP",
    priority: 5,
    transport: "oauth_cloud",
    push: true,
    latencyMin: 10,
    metrics: ["hrv", "heartRate", "respiration", "sleepStages", "recovery", "strain", "calories", "workouts", "spo2", "skinTemp"],
    notes: "WHOOP API v2 z webhookami. Recovery i Day Strain mapujemy odpowiednio na readinessScore i strain.",
  },
  {
    id: "fitbit",
    name: "Fitbit",
    priority: 6,
    transport: "oauth_cloud",
    push: true,
    latencyMin: 15,
    metrics: ["heartRate", "hrv", "spo2", "respiration", "sleepStages", "sleepScore", "steps", "calories", "distance", "workouts", "weight", "skinTemp"],
    notes: "Fitbit Web API z subskrypcjami. Uwaga na limity odpytywania — używamy subskrypcji, nie odpytywania cyklicznego.",
  },
  {
    id: "polar",
    name: "Polar Flow",
    priority: 7,
    transport: "oauth_cloud",
    push: true,
    latencyMin: 20,
    metrics: ["heartRate", "hrv", "sleepStages", "sleepScore", "nightlyRecharge", "steps", "calories", "workouts", "vo2Max"],
    notes: "Polar AccessLink API. Nightly Recharge mapujemy na readinessScore.",
  },
  {
    id: "samsung_health",
    name: "Samsung Health",
    priority: 8,
    transport: "native_sdk",
    push: false,
    latencyMin: 20,
    metrics: ["heartRate", "hrv", "spo2", "sleepStages", "sleepScore", "steps", "calories", "workouts", "weight", "bodyComposition", "stress"],
    notes: "Preferowana ścieżka to Health Connect. Samsung Health SDK tylko tam, gdzie Health Connect nie jest dostępny.",
  },
  {
    id: "suunto",
    name: "Suunto",
    priority: 9,
    transport: "oauth_cloud",
    push: false,
    latencyMin: 30,
    metrics: ["heartRate", "workouts", "steps", "calories", "sleepStages", "vo2Max"],
    notes: "Suunto API (dawniej Movescount). Dane treningowe kompletne, dane dobowe ograniczone.",
  },
  {
    id: "coros",
    name: "COROS",
    priority: 10,
    transport: "oauth_cloud",
    push: false,
    latencyMin: 30,
    metrics: ["heartRate", "hrv", "sleepStages", "steps", "calories", "workouts", "vo2Max"],
    notes: "COROS Open API. Wymaga umowy partnerskiej — planowane w fazie 3.",
  },
  {
    id: "withings",
    name: "Withings",
    priority: 11,
    transport: "oauth_cloud",
    push: true,
    latencyMin: 10,
    metrics: ["weight", "bodyFat", "bloodPressure", "heartRate", "sleepStages", "respiration", "temperature"],
    notes: "Najlepsze źródło masy ciała, składu ciała i ciśnienia — uzupełnia zegarek, nie zastępuje go.",
  },
  {
    id: "huawei_health",
    name: "Huawei Health",
    priority: 12,
    transport: "oauth_cloud",
    push: false,
    latencyMin: 30,
    metrics: ["heartRate", "spo2", "sleepStages", "steps", "calories", "workouts", "stress"],
    notes: "Huawei Health Kit. Wymagany osobny wniosek o zakres danych zdrowotnych.",
  },
  {
    id: "google_fit",
    name: "Google Fit",
    priority: 13,
    transport: "oauth_cloud",
    push: false,
    latencyMin: 30,
    metrics: ["steps", "calories", "distance", "heartRate", "workouts", "weight"],
    notes: "Utrzymywane dla zgodności wstecznej. Nowe instalacje kierujemy na Health Connect.",
  },
  {
    id: "strava",
    name: "Strava",
    priority: 14,
    transport: "oauth_cloud",
    push: true,
    latencyMin: 5,
    metrics: ["workouts", "distance", "calories", "heartRate", "elevation"],
    notes: "Wyłącznie treningi — uzupełnia obraz obciążenia, nie dostarcza danych dobowych ani snu.",
  },
  {
    id: "xiaomi",
    name: "Xiaomi / Amazfit / Zepp",
    priority: 15,
    transport: "native_sdk",
    push: false,
    latencyMin: 60,
    metrics: ["steps", "heartRate", "sleepStages", "spo2", "calories", "stress"],
    notes: "Przez Health Connect (Android). Bezpośrednie API Zepp dostępne tylko dla partnerów.",
  },
  {
    id: "manual",
    name: "Wpis ręczny",
    priority: 16,
    transport: "file_import",
    push: false,
    latencyMin: 0,
    metrics: ["sleep", "mood", "nutrition", "hydration", "weight", "meditation", "alcohol", "nicotine"],
    notes:
      "Zawsze dostępny. Aplikacja jest w pełni użyteczna bez żadnego urządzenia — wtedy wyniki opierają się na dzienniku i mają odpowiednio niższą pewność.",
  },
];

export const getIntegration = (id: DataSource): DeviceIntegration | undefined =>
  DEVICE_INTEGRATIONS.find((d) => d.id === id);

/**
 * Marki zegarków obsługiwane pośrednio — mapowanie na kanał, przez który
 * realnie docierają ich dane. Używane w ekranie „Urządzenia”, żeby użytkownik
 * Amazfita wiedział, że ma połączyć Health Connect, a nie szukać osobnej kafelki.
 */
export const SUPPORTED_BRANDS: Array<{ brand: string; via: DataSource; note: string }> = [
  { brand: "Garmin", via: "garmin", note: "Bezpośrednie połączenie z Garmin Connect" },
  { brand: "Apple Watch", via: "apple_health", note: "Przez Apple Health na iPhonie" },
  { brand: "Samsung Galaxy Watch", via: "health_connect", note: "Przez Health Connect" },
  { brand: "Google Pixel Watch", via: "health_connect", note: "Przez Health Connect (Fitbit OS)" },
  { brand: "Fitbit", via: "fitbit", note: "Bezpośrednio lub przez Health Connect" },
  { brand: "Oura Ring", via: "oura", note: "Bezpośrednie połączenie z Oura Cloud" },
  { brand: "WHOOP", via: "whoop", note: "Bezpośrednie połączenie z WHOOP Cloud" },
  { brand: "Polar", via: "polar", note: "Przez Polar AccessLink" },
  { brand: "Suunto", via: "suunto", note: "Przez Suunto App" },
  { brand: "COROS", via: "coros", note: "Przez COROS Open API" },
  { brand: "Huawei Watch", via: "huawei_health", note: "Przez Huawei Health" },
  { brand: "Xiaomi Watch", via: "xiaomi", note: "Przez Health Connect" },
  { brand: "Amazfit / Zepp", via: "xiaomi", note: "Przez Health Connect" },
  { brand: "Withings", via: "withings", note: "Waga, ciśnieniomierz i mata Sleep" },
  { brand: "OnePlus Watch", via: "health_connect", note: "Przez Health Connect" },
  { brand: "Mobvoi TicWatch", via: "health_connect", note: "Przez Health Connect" },
  { brand: "Nothing Watch", via: "health_connect", note: "Przez Health Connect" },
  { brand: "Honor Watch", via: "health_connect", note: "Przez Health Connect" },
  { brand: "Oppo Watch", via: "health_connect", note: "Przez Health Connect" },
  { brand: "Realme Watch", via: "health_connect", note: "Przez Health Connect" },
];

/**
 * Priorytet źródeł przy scalaniu tej samej metryki z wielu urządzeń.
 * Wyższa liczba wygrywa. Zasada: urządzenie noszone całą dobę na nadgarstku
 * lub palcu ma pierwszeństwo przed telefonem i przed wpisem ręcznym,
 * z wyjątkiem pól, które użytkownik wprowadza świadomie (dieta, nastrój).
 */
export const SOURCE_TRUST: Record<DataSource, number> = {
  garmin: 100,
  oura: 95,
  whoop: 92,
  polar: 88,
  apple_health: 85,
  fitbit: 82,
  suunto: 78,
  coros: 78,
  withings: 76,
  samsung_health: 74,
  health_connect: 72,
  huawei_health: 66,
  amazfit: 62,
  xiaomi: 60,
  google_fit: 55,
  strava: 50,
  manual: 40,
  derived: 10,
};
