-- Add video_url column to tracks table if not exists
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS video_url TEXT;

-- Clear existing tracks to start fresh with seeded data
DELETE FROM public.playlist_tracks;
DELETE FROM public.liked_songs;
DELETE FROM public.listening_history;
DELETE FROM public.tracks;

-- Insert 100 YouTube music tracks (Rock/Punk/Pop 2026 hits)
INSERT INTO public.tracks (title, artist, genre, duration, video_url, cover_url, mood) VALUES
-- Pop hits
('APT.', 'ROSÉ & Bruno Mars', 'Pop', 210, 'https://www.youtube.com/watch?v=ekr2nIex040', 'https://img.youtube.com/vi/ekr2nIex040/maxresdefault.jpg', 'energetic'),
('The Fate of Ophelia', 'Taylor Swift', 'Pop', 245, 'https://www.youtube.com/watch?v=ko70cExuzZM', 'https://img.youtube.com/vi/ko70cExuzZM/maxresdefault.jpg', 'melancholic'),
('Leave Me Alone', 'Reneé Rapp', 'Pop', 198, 'https://www.youtube.com/watch?v=tiPWzFLiz4A', 'https://img.youtube.com/vi/tiPWzFLiz4A/maxresdefault.jpg', 'confident'),
('Die With A Smile', 'Lady Gaga & Bruno Mars', 'Pop', 267, 'https://www.youtube.com/watch?v=kPa7bsKwL-c', 'https://img.youtube.com/vi/kPa7bsKwL-c/maxresdefault.jpg', 'romantic'),
('bad enough', 'Madison Beer', 'Pop', 185, 'https://www.youtube.com/watch?v=07SeT_QSJ08', 'https://img.youtube.com/vi/07SeT_QSJ08/maxresdefault.jpg', 'moody'),
('BIRDS OF A FEATHER', 'Billie Eilish', 'Pop', 212, 'https://www.youtube.com/watch?v=V9PVRfjEBTI', 'https://img.youtube.com/vi/V9PVRfjEBTI/maxresdefault.jpg', 'dreamy'),
('Ordinary', 'Alex Warren', 'Pop-Rock', 224, 'https://www.youtube.com/watch?v=u2ah9tWTkmk', 'https://img.youtube.com/vi/u2ah9tWTkmk/maxresdefault.jpg', 'reflective'),
('Beautiful Things', 'Benson Boone', 'Pop-Rock', 238, 'https://www.youtube.com/watch?v=Oa_RSwwpPaA', 'https://img.youtube.com/vi/Oa_RSwwpPaA/maxresdefault.jpg', 'emotional'),
('WILDFLOWER', 'Billie Eilish', 'Pop', 265, 'https://www.youtube.com/watch?v=IWKyykQBRKo', 'https://img.youtube.com/vi/IWKyykQBRKo/maxresdefault.jpg', 'introspective'),
('Higher', 'J-Summa', 'Pop', 195, 'https://www.youtube.com/watch?v=35ZkGt03DAs', 'https://img.youtube.com/vi/35ZkGt03DAs/maxresdefault.jpg', 'uplifting'),
('WHERE IS MY HUSBAND!', 'RAYE', 'Pop', 178, 'https://www.youtube.com/watch?v=rK5TyISxZ_M', 'https://img.youtube.com/vi/rK5TyISxZ_M/maxresdefault.jpg', 'dramatic'),
('Damn I Love Miami', 'Pitbull & Lil Jon', 'Pop', 192, 'https://www.youtube.com/watch?v=Cj1SCv5HkKE', 'https://img.youtube.com/vi/Cj1SCv5HkKE/maxresdefault.jpg', 'party'),
('Espresso', 'Sabrina Carpenter', 'Pop', 175, 'https://www.youtube.com/watch?v=eVli-tstM5E', 'https://img.youtube.com/vi/eVli-tstM5E/maxresdefault.jpg', 'flirty'),
('Sapphire', 'Ed Sheeran', 'Pop', 232, 'https://www.youtube.com/watch?v=JgDNFQ2RaLQ', 'https://img.youtube.com/vi/JgDNFQ2RaLQ/maxresdefault.jpg', 'romantic'),
-- Punk-Rock hits
('Zombie', 'YUNGBLUD', 'Punk-Rock', 198, 'https://www.youtube.com/watch?v=Yv97b2oPk3w', 'https://img.youtube.com/vi/Yv97b2oPk3w/maxresdefault.jpg', 'aggressive'),
('Chemical', 'Post Malone', 'Pop-Rock', 215, 'https://www.youtube.com/watch?v=IzPQ_jA00bk', 'https://img.youtube.com/vi/IzPQ_jA00bk/maxresdefault.jpg', 'melancholic'),
('Eyes Closed', 'Imagine Dragons', 'Rock', 245, 'https://www.youtube.com/watch?v=v08qmr8m_-w', 'https://img.youtube.com/vi/v08qmr8m_-w/maxresdefault.jpg', 'powerful'),
('bad idea right?', 'Olivia Rodrigo', 'Pop-Punk', 189, 'https://www.youtube.com/watch?v=Dj9qJsJTsjQ', 'https://img.youtube.com/vi/Dj9qJsJTsjQ/maxresdefault.jpg', 'rebellious'),
('Cry', 'Benson Boone', 'Pop-Rock', 205, 'https://www.youtube.com/watch?v=i828eLpviiY', 'https://img.youtube.com/vi/i828eLpviiY/maxresdefault.jpg', 'emotional'),
('Young & Dumb', 'Avril Lavigne ft. Simple Plan', 'Pop-Punk', 198, 'https://www.youtube.com/watch?v=gRX3Gm-YPRY', 'https://img.youtube.com/vi/gRX3Gm-YPRY/maxresdefault.jpg', 'nostalgic'),
('feelslikeimfallinginlove', 'Coldplay', 'Rock', 276, 'https://www.youtube.com/watch?v=V3IVdLo-2NM', 'https://img.youtube.com/vi/V3IVdLo-2NM/maxresdefault.jpg', 'euphoric'),
('ALL MY LOVE', 'Coldplay', 'Rock', 258, 'https://www.youtube.com/watch?v=pSeaHfkd3M8', 'https://img.youtube.com/vi/pSeaHfkd3M8/maxresdefault.jpg', 'loving'),
('Pretty Slowly', 'Benson Boone', 'Pop-Rock', 212, 'https://www.youtube.com/watch?v=4BuWrb8A_w4', 'https://img.youtube.com/vi/4BuWrb8A_w4/maxresdefault.jpg', 'tender'),
('Invincible', 'OneRepublic', 'Pop-Rock', 224, 'https://www.youtube.com/watch?v=_CcXxtgQgIA', 'https://img.youtube.com/vi/_CcXxtgQgIA/maxresdefault.jpg', 'empowering'),
('NOT OK', '5 Seconds of Summer', 'Pop-Rock', 187, 'https://www.youtube.com/watch?v=OOHndihD7Dc', 'https://img.youtube.com/vi/OOHndihD7Dc/maxresdefault.jpg', 'angsty'),
('Nice to Meet You', 'Imagine Dragons', 'Rock', 235, 'https://www.youtube.com/watch?v=NeUfmyu5t8Q', 'https://img.youtube.com/vi/NeUfmyu5t8Q/maxresdefault.jpg', 'hopeful'),
('Fire In These Hills', 'Imagine Dragons', 'Rock', 248, 'https://www.youtube.com/watch?v=baYqOdpsqbg', 'https://img.youtube.com/vi/baYqOdpsqbg/maxresdefault.jpg', 'intense'),
('RUNAWAY', 'OneRepublic', 'Pop-Rock', 215, 'https://www.youtube.com/watch?v=qWJU_eANW4M', 'https://img.youtube.com/vi/qWJU_eANW4M/maxresdefault.jpg', 'adventurous'),
('Tell Me', 'Teddy Swims', 'Pop-Rock', 198, 'https://www.youtube.com/watch?v=3CDaO3x75FE', 'https://img.youtube.com/vi/3CDaO3x75FE/maxresdefault.jpg', 'soulful'),
('Be Someone', 'Benson Boone', 'Pop-Rock', 208, 'https://www.youtube.com/watch?v=I9qxHs761Cg', 'https://img.youtube.com/vi/I9qxHs761Cg/maxresdefault.jpg', 'aspirational'),
('Man In The Moon', 'Coldplay', 'Rock', 285, 'https://www.youtube.com/watch?v=f9Jpualtehw', 'https://img.youtube.com/vi/f9Jpualtehw/maxresdefault.jpg', 'dreamy'),
('I Ain''t Worried', 'OneRepublic', 'Pop-Rock', 152, 'https://www.youtube.com/watch?v=mNEUkkoUoIA', 'https://img.youtube.com/vi/mNEUkkoUoIA/maxresdefault.jpg', 'carefree'),
('Bones', 'Imagine Dragons', 'Rock', 165, 'https://www.youtube.com/watch?v=TO-_3tck2tg', 'https://img.youtube.com/vi/TO-_3tck2tg/maxresdefault.jpg', 'dark'),
('Bad Life', 'Sigrid & Bring Me The Horizon', 'Rock', 198, 'https://www.youtube.com/watch?v=o4552tadeuM', 'https://img.youtube.com/vi/o4552tadeuM/maxresdefault.jpg', 'defiant'),
('10 Things I Hate About You', 'Leah Kate', 'Pop-Punk', 175, 'https://www.youtube.com/watch?v=BMFzGs9IOmM', 'https://img.youtube.com/vi/BMFzGs9IOmM/maxresdefault.jpg', 'angry'),
-- Punk classics
('Tissues', 'YUNGBLUD', 'Punk', 188, 'https://www.youtube.com/watch?v=fI9ztgoZ5yQ', 'https://img.youtube.com/vi/fI9ztgoZ5yQ/maxresdefault.jpg', 'vulnerable'),
('Endless Possibility', 'Bowling For Soup, Punk Rock Factory, Wheatus', 'Pop-Punk', 225, 'https://www.youtube.com/watch?v=sr96GLGRplQ', 'https://img.youtube.com/vi/sr96GLGRplQ/maxresdefault.jpg', 'optimistic'),
('Lovesick Lullaby', 'YUNGBLUD', 'Punk', 195, 'https://www.youtube.com/watch?v=WfwUrz7s_Vg', 'https://img.youtube.com/vi/WfwUrz7s_Vg/maxresdefault.jpg', 'heartbroken'),
('vampire diaries', 'mgk', 'Pop-Punk', 182, 'https://www.youtube.com/watch?v=_vsPcevFIyk', 'https://img.youtube.com/vi/_vsPcevFIyk/maxresdefault.jpg', 'dark'),
('Wake Me Up When September Ends', 'Green Day', 'Punk-Rock', 285, 'https://www.youtube.com/watch?v=pGhwBFYtn1s', 'https://img.youtube.com/vi/pGhwBFYtn1s/maxresdefault.jpg', 'melancholic'),
('cliché', 'mgk', 'Pop-Punk', 178, 'https://www.youtube.com/watch?v=m4DVbm9zeR0', 'https://img.youtube.com/vi/m4DVbm9zeR0/maxresdefault.jpg', 'rebellious'),
('Ok, But This Is The Last Time', 'The Offspring', 'Punk', 195, 'https://www.youtube.com/watch?v=7gKc2_COfGc', 'https://img.youtube.com/vi/7gKc2_COfGc/maxresdefault.jpg', 'frustrated'),
('Dilemma', 'Green Day', 'Punk-Rock', 188, 'https://www.youtube.com/watch?v=qAmulKjcHoo', 'https://img.youtube.com/vi/qAmulKjcHoo/maxresdefault.jpg', 'conflicted'),
('We Didn''t Start the Fire', 'Fall Out Boy', 'Pop-Punk', 248, 'https://www.youtube.com/watch?v=2LkVKCWL0U4', 'https://img.youtube.com/vi/2LkVKCWL0U4/maxresdefault.jpg', 'chaotic'),
('DANCE WITH ME', 'blink-182', 'Punk', 195, 'https://www.youtube.com/watch?v=LUEYNuVeA9Y', 'https://img.youtube.com/vi/LUEYNuVeA9Y/maxresdefault.jpg', 'playful'),
('New Gold Magic', 'Econoline Crush', 'Rock', 212, 'https://www.youtube.com/watch?v=nrunO7NyDYM', 'https://img.youtube.com/vi/nrunO7NyDYM/maxresdefault.jpg', 'hypnotic'),
('all-american bitch', 'Olivia Rodrigo', 'Pop-Punk', 165, 'https://www.youtube.com/watch?v=n2BnbpjpRdo', 'https://img.youtube.com/vi/n2BnbpjpRdo/maxresdefault.jpg', 'sarcastic'),
('LosT', 'Bring Me The Horizon', 'Rock', 235, 'https://www.youtube.com/watch?v=xv-70a6yXfM', 'https://img.youtube.com/vi/xv-70a6yXfM/maxresdefault.jpg', 'intense'),
('DANCER', 'IDLES', 'Punk', 178, 'https://www.youtube.com/watch?v=A3ZZj5y6Qt4', 'https://img.youtube.com/vi/A3ZZj5y6Qt4/maxresdefault.jpg', 'energetic'),
('ANTHEM PART 3', 'blink-182', 'Punk', 188, 'https://www.youtube.com/watch?v=lv-cOIuJ1k0', 'https://img.youtube.com/vi/lv-cOIuJ1k0/maxresdefault.jpg', 'anthemic'),
-- Classic Punk
('The Kids Aren''t Alright', 'The Offspring', 'Punk', 180, 'https://www.youtube.com/watch?v=7iNbnineUCI', 'https://img.youtube.com/vi/7iNbnineUCI/maxresdefault.jpg', 'rebellious'),
('Teenage Dirtbag', 'Wheatus', 'Pop-Punk', 245, 'https://www.youtube.com/watch?v=FC3y9llDXuM', 'https://img.youtube.com/vi/FC3y9llDXuM/maxresdefault.jpg', 'nostalgic'),
('Centuries', 'Fall Out Boy', 'Pop-Punk', 235, 'https://www.youtube.com/watch?v=LBr7kECsjcQ', 'https://img.youtube.com/vi/LBr7kECsjcQ/maxresdefault.jpg', 'epic'),
('You''re Gonna Go Far, Kid', 'The Offspring', 'Punk', 178, 'https://www.youtube.com/watch?v=ql9-82oV2JE', 'https://img.youtube.com/vi/ql9-82oV2JE/maxresdefault.jpg', 'aggressive'),
('Welcome To The Black Parade', 'My Chemical Romance', 'Pop-Punk', 312, 'https://www.youtube.com/watch?v=RRKJiM9Njr8', 'https://img.youtube.com/vi/RRKJiM9Njr8/maxresdefault.jpg', 'anthemic'),
('Should I Stay or Should I Go', 'The Clash', 'Punk', 188, 'https://www.youtube.com/watch?v=xMaE6toi4mk', 'https://img.youtube.com/vi/xMaE6toi4mk/maxresdefault.jpg', 'conflicted'),
('Basket Case', 'Green Day', 'Punk-Rock', 182, 'https://www.youtube.com/watch?v=NUTGr5t3MoY', 'https://img.youtube.com/vi/NUTGr5t3MoY/maxresdefault.jpg', 'anxious'),
('Teenagers', 'My Chemical Romance', 'Pop-Punk', 178, 'https://www.youtube.com/watch?v=k6EQAOmJrbw', 'https://img.youtube.com/vi/k6EQAOmJrbw/maxresdefault.jpg', 'rebellious'),
('All The Small Things', 'blink-182', 'Punk', 167, 'https://www.youtube.com/watch?v=9Ht5RZpzPqw', 'https://img.youtube.com/vi/9Ht5RZpzPqw/maxresdefault.jpg', 'happy'),
('Savior', 'Rise Against', 'Punk-Rock', 245, 'https://www.youtube.com/watch?v=e8X3ACToii0', 'https://img.youtube.com/vi/e8X3ACToii0/maxresdefault.jpg', 'passionate'),
('Perfect', 'Simple Plan', 'Pop-Punk', 265, 'https://www.youtube.com/watch?v=RUi54JTgL5s', 'https://img.youtube.com/vi/RUi54JTgL5s/maxresdefault.jpg', 'emotional'),
('Misery Business', 'Paramore', 'Pop-Punk', 228, 'https://www.youtube.com/watch?v=aCyGvGEtOwc', 'https://img.youtube.com/vi/aCyGvGEtOwc/maxresdefault.jpg', 'angry'),
('American Idiot', 'Green Day', 'Punk-Rock', 178, 'https://www.youtube.com/watch?v=Ee_uujKuJMI', 'https://img.youtube.com/vi/Ee_uujKuJMI/maxresdefault.jpg', 'political'),
('The Middle', 'Jimmy Eat World', 'Pop-Rock', 165, 'https://www.youtube.com/watch?v=oKsxPW6i3pM', 'https://img.youtube.com/vi/oKsxPW6i3pM/maxresdefault.jpg', 'encouraging'),
('What''s My Age Again?', 'blink-182', 'Punk', 148, 'https://www.youtube.com/watch?v=K7l5ZeVVoCA', 'https://img.youtube.com/vi/K7l5ZeVVoCA/maxresdefault.jpg', 'immature'),
('In Too Deep', 'Sum 41', 'Pop-Punk', 212, 'https://www.youtube.com/watch?v=emGri7i8Y2Y', 'https://img.youtube.com/vi/emGri7i8Y2Y/maxresdefault.jpg', 'regretful'),
('Face Down', 'The Red Jumpsuit Apparatus', 'Pop-Punk', 235, 'https://www.youtube.com/watch?v=6Ux6SlOE9Qk', 'https://img.youtube.com/vi/6Ux6SlOE9Qk/maxresdefault.jpg', 'protective'),
('Dear Maria, Count Me In', 'All Time Low', 'Pop-Punk', 178, 'https://www.youtube.com/watch?v=GcNiKCmWdYE', 'https://img.youtube.com/vi/GcNiKCmWdYE/maxresdefault.jpg', 'fun'),
('My Happy Ending', 'Avril Lavigne', 'Pop-Punk', 245, 'https://www.youtube.com/watch?v=s8QYxmpuyxg', 'https://img.youtube.com/vi/s8QYxmpuyxg/maxresdefault.jpg', 'bitter'),
('Dirty Little Secret', 'The All-American Rejects', 'Pop-Rock', 195, 'https://www.youtube.com/watch?v=gPDcwjJ8pLg', 'https://img.youtube.com/vi/gPDcwjJ8pLg/maxresdefault.jpg', 'secretive'),
('Girlfriend', 'Avril Lavigne', 'Pop-Punk', 218, 'https://www.youtube.com/watch?v=Bg59q4puhmg', 'https://img.youtube.com/vi/Bg59q4puhmg/maxresdefault.jpg', 'bratty'),
('Thnks fr th Mmrs', 'Fall Out Boy', 'Pop-Punk', 205, 'https://www.youtube.com/watch?v=onzL0EM1pKY', 'https://img.youtube.com/vi/onzL0EM1pKY/maxresdefault.jpg', 'sarcastic'),
('Pretty Fly (For A White Guy)', 'The Offspring', 'Punk', 198, 'https://www.youtube.com/watch?v=QtTR-_Klcq8', 'https://img.youtube.com/vi/QtTR-_Klcq8/maxresdefault.jpg', 'humorous'),
('Dance, Dance', 'Fall Out Boy', 'Pop-Punk', 182, 'https://www.youtube.com/watch?v=C6MOKXm8x50', 'https://img.youtube.com/vi/C6MOKXm8x50/maxresdefault.jpg', 'upbeat'),
('Sk8er Boi', 'Avril Lavigne', 'Pop-Punk', 203, 'https://www.youtube.com/watch?v=TIy3n2b7V9k', 'https://img.youtube.com/vi/TIy3n2b7V9k/maxresdefault.jpg', 'rebellious'),
('Holiday', 'Green Day', 'Punk-Rock', 232, 'https://www.youtube.com/watch?v=A1OqtIqzScI', 'https://img.youtube.com/vi/A1OqtIqzScI/maxresdefault.jpg', 'political'),
('Disenchanted', 'My Chemical Romance', 'Pop-Punk', 285, 'https://www.youtube.com/watch?v=j_MlBCb9-m8', 'https://img.youtube.com/vi/j_MlBCb9-m8/maxresdefault.jpg', 'sad'),
('When I Come Around', 'Green Day', 'Punk-Rock', 178, 'https://www.youtube.com/watch?v=i8dh9gDzmz8', 'https://img.youtube.com/vi/i8dh9gDzmz8/maxresdefault.jpg', 'casual'),
('Sugar, We''re Goin Down', 'Fall Out Boy', 'Pop-Punk', 228, 'https://www.youtube.com/watch?v=uhG-vLZrb-g', 'https://img.youtube.com/vi/uhG-vLZrb-g/maxresdefault.jpg', 'hopeful'),
('That''s What You Get', 'Paramore', 'Pop-Punk', 245, 'https://www.youtube.com/watch?v=1kz6hNDlEEg', 'https://img.youtube.com/vi/1kz6hNDlEEg/maxresdefault.jpg', 'defiant'),
('I''m Not Okay (I Promise)', 'My Chemical Romance', 'Pop-Punk', 189, 'https://www.youtube.com/watch?v=dhZTNgAs4Fc', 'https://img.youtube.com/vi/dhZTNgAs4Fc/maxresdefault.jpg', 'angsty'),
('My Own Worst Enemy', 'Lit', 'Pop-Punk', 175, 'https://www.youtube.com/watch?v=sc5iTNVEOAg', 'https://img.youtube.com/vi/sc5iTNVEOAg/maxresdefault.jpg', 'regretful'),
('First Date', 'blink-182', 'Punk', 182, 'https://www.youtube.com/watch?v=vVy9Lgpg1m8', 'https://img.youtube.com/vi/vVy9Lgpg1m8/maxresdefault.jpg', 'nervous'),
('Want You Bad', 'The Offspring', 'Punk', 185, 'https://www.youtube.com/watch?v=_g19fCJotPc', 'https://img.youtube.com/vi/_g19fCJotPc/maxresdefault.jpg', 'lustful'),
('Welcome To My Life', 'Simple Plan', 'Pop-Punk', 232, 'https://www.youtube.com/watch?v=r0U0AlLVqpk', 'https://img.youtube.com/vi/r0U0AlLVqpk/maxresdefault.jpg', 'lonely'),
('The Anthem', 'Good Charlotte', 'Pop-Punk', 178, 'https://www.youtube.com/watch?v=desJKYvdq9A', 'https://img.youtube.com/vi/desJKYvdq9A/maxresdefault.jpg', 'rebellious'),
('Ocean Avenue', 'Yellowcard', 'Pop-Punk', 195, 'https://www.youtube.com/watch?v=X9fLbfzCqWw', 'https://img.youtube.com/vi/X9fLbfzCqWw/maxresdefault.jpg', 'nostalgic'),
('Adam''s Song', 'blink-182', 'Punk', 265, 'https://www.youtube.com/watch?v=2MRdtXWcgIw', 'https://img.youtube.com/vi/2MRdtXWcgIw/maxresdefault.jpg', 'depressed'),
('Ignorance', 'Paramore', 'Pop-Punk', 215, 'https://www.youtube.com/watch?v=OH9A6tn_P6g', 'https://img.youtube.com/vi/OH9A6tn_P6g/maxresdefault.jpg', 'angry'),
('Stay Together For The Kids', 'blink-182', 'Punk', 245, 'https://www.youtube.com/watch?v=k1BFHYtZlAU', 'https://img.youtube.com/vi/k1BFHYtZlAU/maxresdefault.jpg', 'sad'),
('1985', 'Bowling For Soup', 'Pop-Punk', 195, 'https://www.youtube.com/watch?v=K38xNqZvBJI', 'https://img.youtube.com/vi/K38xNqZvBJI/maxresdefault.jpg', 'nostalgic'),
('crushcrushcrush', 'Paramore', 'Pop-Punk', 202, 'https://www.youtube.com/watch?v=ei8hPkyJ0bU', 'https://img.youtube.com/vi/ei8hPkyJ0bU/maxresdefault.jpg', 'frustrated'),
('The Great Escape', 'Boys Like Girls', 'Pop-Punk', 215, 'https://www.youtube.com/watch?v=JGPgxoIPY6Q', 'https://img.youtube.com/vi/JGPgxoIPY6Q/maxresdefault.jpg', 'adventurous'),
('Jet Lag ft. Natasha Bedingfield', 'Simple Plan', 'Pop-Punk', 225, 'https://www.youtube.com/watch?v=ntSBKPkk4m4', 'https://img.youtube.com/vi/ntSBKPkk4m4/maxresdefault.jpg', 'longing'),
('This Ain''t A Scene, It''s An Arms Race', 'Fall Out Boy', 'Pop-Punk', 205, 'https://www.youtube.com/watch?v=GNm5drtAQXs', 'https://img.youtube.com/vi/GNm5drtAQXs/maxresdefault.jpg', 'sarcastic'),
('Move Along', 'The All-American Rejects', 'Pop-Rock', 225, 'https://www.youtube.com/watch?v=XleOkGsYgO8', 'https://img.youtube.com/vi/XleOkGsYgO8/maxresdefault.jpg', 'motivational'),
('Bloody Valentine', 'Machine Gun Kelly', 'Pop-Punk', 232, 'https://www.youtube.com/watch?v=wSdT-SArM2Q', 'https://img.youtube.com/vi/wSdT-SArM2Q/maxresdefault.jpg', 'chaotic'),
('Dammit', 'blink-182', 'Punk', 162, 'https://www.youtube.com/watch?v=sT0g16_LQaQ', 'https://img.youtube.com/vi/sT0g16_LQaQ/maxresdefault.jpg', 'frustrated'),
('I Think I''m OKAY', 'Machine Gun Kelly', 'Pop-Punk', 245, 'https://www.youtube.com/watch?v=wK-8TCDrbV8', 'https://img.youtube.com/vi/wK-8TCDrbV8/maxresdefault.jpg', 'anxious'),
('Lifestyles of the Rich & Famous', 'Good Charlotte', 'Pop-Punk', 195, 'https://www.youtube.com/watch?v=y-jC3H_8Dk4', 'https://img.youtube.com/vi/y-jC3H_8Dk4/maxresdefault.jpg', 'sarcastic');