-- Link Paddle prices to storage plans
UPDATE public.aurora_storage_plans SET paddle_price_id = 'aurora_storage_starter_monthly' WHERE code = 'r2_starter_10gb';
UPDATE public.aurora_storage_plans SET paddle_price_id = 'aurora_storage_pro_monthly' WHERE code = 'r2_pro_50gb';
UPDATE public.aurora_storage_plans SET paddle_price_id = 'aurora_storage_business_monthly' WHERE code = 'r2_business_200gb';

-- Settings table for R2 / Aurora storage configuration (singleton row)
CREATE TABLE IF NOT EXISTS public.aurora_r2_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bucket_name text NOT NULL DEFAULT '',
  public_base_url text NOT NULL DEFAULT '',
  default_signed_ttl_days integer NOT NULL DEFAULT 7,
  margin_percent numeric(5,2) NOT NULL DEFAULT 60.00,
  cost_per_gb_eur numeric(8,4) NOT NULL DEFAULT 0.0135,
  cost_per_gb_egress_eur numeric(8,4) NOT NULL DEFAULT 0.0000,
  allow_public_assets boolean NOT NULL DEFAULT true,
  hard_block_on_quota boolean NOT NULL DEFAULT true,
  notes text,
  updated_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Seed singleton row
INSERT INTO public.aurora_r2_settings (bucket_name, public_base_url)
SELECT '', 'https://pub-46ecdc3a5ae341fcb16454d732eb9bcd.r2.dev'
WHERE NOT EXISTS (SELECT 1 FROM public.aurora_r2_settings);

ALTER TABLE public.aurora_r2_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin manage r2 settings"
  ON public.aurora_r2_settings FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE TRIGGER trg_r2_settings_touch
  BEFORE UPDATE ON public.aurora_r2_settings
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- Storage offers (proposals generated by Aurora for clients)
CREATE TABLE IF NOT EXISTS public.aurora_storage_offers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_email text NOT NULL,
  client_company text,
  recommended_plan_code text REFERENCES public.aurora_storage_plans(code),
  current_usage_gb numeric(10,3) NOT NULL DEFAULT 0,
  projected_usage_gb numeric(10,3) NOT NULL DEFAULT 0,
  monthly_price_eur numeric(10,2) NOT NULL DEFAULT 0,
  margin_eur numeric(10,2) NOT NULL DEFAULT 0,
  rationale text,
  status text NOT NULL DEFAULT 'draft',
  expires_at timestamptz,
  checkout_url text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.aurora_storage_offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin manage offers"
  ON public.aurora_storage_offers FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE TRIGGER trg_storage_offers_touch
  BEFORE UPDATE ON public.aurora_storage_offers
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX IF NOT EXISTS idx_storage_offers_email ON public.aurora_storage_offers(client_email);
CREATE INDEX IF NOT EXISTS idx_storage_offers_status ON public.aurora_storage_offers(status);

-- Helper view: per-client usage rollup with cost & margin
CREATE OR REPLACE VIEW public.aurora_storage_client_usage AS
SELECT
  s.id AS subscription_id,
  s.client_email,
  s.client_company,
  s.client_user_id,
  s.plan_code,
  p.name AS plan_name,
  p.storage_gb AS plan_storage_gb,
  p.price_eur AS plan_price_eur,
  s.status,
  s.storage_used_bytes,
  ROUND(s.storage_used_bytes / 1073741824.0, 3) AS storage_used_gb,
  ROUND((s.storage_used_bytes / 1073741824.0) / NULLIF(p.storage_gb, 0) * 100, 1) AS usage_percent,
  ROUND((s.storage_used_bytes / 1073741824.0) * (
    SELECT cost_per_gb_eur FROM public.aurora_r2_settings LIMIT 1
  ), 4) AS estimated_cost_eur,
  s.current_period_end,
  s.paddle_subscription_id
FROM public.aurora_storage_subscriptions s
LEFT JOIN public.aurora_storage_plans p ON p.code = s.plan_code;

-- RPC: fulfill storage subscription from Paddle webhook
CREATE OR REPLACE FUNCTION public.aurora_storage_fulfill_from_paddle(
  _user_id uuid,
  _email text,
  _price_external_id text,
  _paddle_subscription_id text,
  _current_period_end timestamptz,
  _status text
) RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _plan_code text;
  _sub_id uuid;
BEGIN
  SELECT code INTO _plan_code
  FROM public.aurora_storage_plans
  WHERE paddle_price_id = _price_external_id
  LIMIT 1;

  IF _plan_code IS NULL THEN
    RETURN NULL;
  END IF;

  -- Try to find existing subscription by paddle id
  SELECT id INTO _sub_id
  FROM public.aurora_storage_subscriptions
  WHERE paddle_subscription_id = _paddle_subscription_id
  LIMIT 1;

  IF _sub_id IS NOT NULL THEN
    UPDATE public.aurora_storage_subscriptions
    SET plan_code = _plan_code,
        client_email = COALESCE(_email, client_email),
        client_user_id = COALESCE(_user_id, client_user_id),
        status = _status,
        current_period_end = _current_period_end,
        updated_at = now()
    WHERE id = _sub_id;
  ELSE
    INSERT INTO public.aurora_storage_subscriptions
      (plan_code, client_email, client_user_id, status, current_period_end, paddle_subscription_id)
    VALUES
      (_plan_code, _email, _user_id, _status, _current_period_end, _paddle_subscription_id)
    RETURNING id INTO _sub_id;
  END IF;

  RETURN _sub_id;
END;
$$;